matrix:
    include:
        -
            language: go
            go:
                - 1.8
                - 1.9
            install:
                - go get github.com/go-ozzo/ozzo-config
                - go get github.com/go-ozzo/ozzo-log
            script:
                - cd srv-src && sh build.sh
        -
            language: php
            php:
                - 7.0.25
            script:
                - cd ext-src && sh build.sh

env:
   - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

notifications:
    email: false
